//! Build tasks for the workspace.
//!
//! ```text
//! cargo xtask fetch        download the artefacts into spec/
//! cargo xtask codegen      regenerate every derived table from spec/
//! cargo xtask check        regenerate into memory and fail if anything differs
//! ```
//!
//! # One runner, two crates, one `spec/`
//!
//! Both crates derive tables from the *same* four upstream artefact
//! repositories at the *same* pinned revision. Split across two repositories
//! that meant two near-identical `fetch.rs`, two `spec/` trees of the same
//! 136 MB, and two `CEN_REF` constants kept equal by hand. Here it is one fetch,
//! one pin, and one `cargo xtask check` that gates every generated file in the
//! workspace.
//!
//! # What is generated, and why none of it is hand-written
//!
//! | Table | Crate | Why it cannot be written by hand |
//! |---|---|---|
//! | [`codes`] | `en16931` | ~4 400 code values across eighteen lists, 2 162 unit codes alone. A wrong unit code is a rejected invoice. |
//! | [`order`] | `en16931-formats` | Both content models are XSD `sequence`s, so right elements in the wrong order is invalid — and no *rule* reports it, because ordering is the schema's job. The order is evidence, topologically sorted from 490 published instances. |
//! | [`prohibitions`] | `en16931-formats` | 1 220 of the 1 339 syntax rules say some element "shall not be used", each *context-relative*. Dropping the context turns a narrow prohibition into a blanket one, and did. |
//!
//! # Why the extraction is careful
//!
//! A Schematron `test` is a **program**, not a data structure. `BR-CL-01`'s test
//! is a disjunction over `self::` with *two* different lists — 50 codes for
//! `cbc:InvoiceTypeCode` and 13 for `cbc:CreditNoteTypeCode`. An extractor that
//! takes the first `contains(…)` literal and stops reports a confident, precise,
//! wrong answer. So every table declares how its list is selected, and the
//! generator **fails** when the artefact does not match that declaration.
//!
//! # Why an xtask and not a script
//!
//! The generators are compiled, type-checked and linted like the rest of the
//! workspace, and need no toolchain it does not already require. `cargo xtask
//! check` runs in CI, so a committed table cannot drift away from the artefacts
//! it claims to come from.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

mod codes;
mod fetch;
mod order;
mod prohibitions;

/// The header every generated file carries.
fn header(title: &str, body: &str) -> String {
    format!(
        "//! {title}\n//!\n\
         //! **Generated by `cargo xtask codegen`. Do not edit.**\n//!\n{body}"
    )
}

/// A Rust string literal's contents, escaped.
///
/// Element names cannot contain a quote or a backslash, so this is defensive
/// rather than load-bearing — but a generator that emits invalid Rust when the
/// input surprises it is worse than one that escapes for nothing.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Shared by both syntax generators: local element name, prefix stripped.
fn local(name: &str) -> &str {
    name.rsplit(':').next().unwrap_or(name)
}

/// A stable, sorted map — used so output is byte-identical across runs.
type Table = BTreeMap<String, Vec<String>>;
/// A stable, sorted set.
type Set = BTreeSet<String>;

/// The workspace root — the directory holding the `[workspace]` manifest.
///
/// `xtask/` sits directly under it, so this is one `parent()` regardless of
/// where cargo was invoked from.
fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask/ has a parent")
        .to_path_buf()
}

/// The directory of a workspace member.
///
/// Every generated file lands under one of these, and routing through a named
/// function is what keeps `crates/` from being spelled out in four generators.
fn member(name: &str) -> PathBuf {
    root().join("crates").join(name)
}

/// Where the artefacts are, if anywhere.
///
/// Not committed: the CEN artefacts are EUPL-1.2, a reciprocal licence, and
/// keeping them out of the repository is what keeps both crates
/// `MIT OR Apache-2.0`.
fn spec() -> Result<PathBuf, String> {
    let p = root().join("spec");
    if p.is_dir() {
        Ok(p)
    } else {
        Err("no spec/ directory — run `cargo xtask fetch`".to_owned())
    }
}

fn read(spec: &Path, rel: &str) -> Result<String, String> {
    let p = spec.join(rel);
    std::fs::read_to_string(&p).map_err(|e| format!("{}: {e}", p.display()))
}

/// Every `.xml` file under `dir`, recursively.
fn xml_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            xml_files(&p, out);
        } else if p.extension().is_some_and(|x| x == "xml") {
            out.push(p);
        }
    }
}

/// A file this runner owns, and what it should contain.
pub struct Generated {
    pub path: PathBuf,
    pub contents: String,
}

impl Generated {
    fn write(&self) -> std::io::Result<()> {
        if let Some(parent) = self.path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&self.path, &self.contents)
    }

    /// Whether the file on disk already matches.
    ///
    /// Compared after normalising line endings, so a Windows checkout does not
    /// report every generated file as stale.
    fn is_current(&self) -> bool {
        std::fs::read_to_string(&self.path)
            .map(|on_disk| on_disk.replace("\r\n", "\n") == self.contents.replace("\r\n", "\n"))
            .unwrap_or(false)
    }
}

/// Run the source through `rustfmt`.
///
/// Without this, `cargo xtask check` fails immediately after `cargo fmt`: the
/// generators' line breaks and rustfmt's disagree, so a freshly generated file
/// and a committed one never match. Formatting here makes the generator's output
/// the same artefact the repository stores, which is the only way `check` can be
/// a useful CI gate.
///
/// If `rustfmt` is not on `PATH` the source is returned unchanged and `check`
/// will report a difference — noisy, but honest, and better than silently
/// comparing two things that were never going to be equal.
fn rustfmt(source: &str) -> String {
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    let Ok(mut child) = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
    else {
        eprintln!("warning: rustfmt not found — generated files will not be formatted");
        return source.to_owned();
    };
    if let Some(stdin) = child.stdin.as_mut() {
        let _ = stdin.write_all(source.as_bytes());
    }
    match child.wait_with_output() {
        Ok(out) if out.status.success() => String::from_utf8_lossy(&out.stdout).into_owned(),
        _ => {
            eprintln!("warning: rustfmt failed — emitting unformatted source");
            source.to_owned()
        }
    }
}

/// Every generated file in the workspace, in one pass over `spec/`.
fn generate() -> Result<Vec<Generated>, String> {
    let spec = spec()?;
    let mut out = Vec::new();

    // `en16931` — the code lists.
    let (source, log) = codes::generate(&spec)?;
    for line in &log {
        println!("{line}");
    }
    out.push(Generated {
        path: member("en16931")
            .join("src")
            .join("codes")
            .join("generated.rs"),
        contents: source,
    });

    // `en16931-formats` — element order and prohibitions, per syntax.
    let mut files = Vec::new();
    xml_files(&spec, &mut files);
    let formats = member("en16931-formats");
    for syntax in [order::Syntax::Ubl, order::Syntax::Cii] {
        out.push(order::derive(syntax, &files, &formats)?);
        out.push(prohibitions::extract(syntax, &spec, &formats)?);
    }

    for g in &mut out {
        g.contents = rustfmt(&g.contents);
    }
    Ok(out)
}

const USAGE: &str = "\
usage: cargo xtask <task>

  fetch     download the artefacts into spec/
  codegen   regenerate every derived table from spec/
  check     regenerate and fail if any committed table differs
";

fn run(check_only: bool) -> Result<(), String> {
    let generated = generate()?;
    let mut stale = Vec::new();
    for g in &generated {
        let rel = g.path.strip_prefix(root()).unwrap_or(&g.path).display();
        if g.is_current() {
            println!("  up to date  {rel}");
            continue;
        }
        if check_only {
            stale.push(rel.to_string());
        } else {
            g.write().map_err(|e| format!("{rel}: {e}"))?;
            println!("  written     {rel}");
        }
    }
    if stale.is_empty() {
        if !check_only {
            println!("regeneration is deterministic: re-running produces byte-identical files");
        }
        return Ok(());
    }
    Err(format!(
        "{} generated file(s) do not match the artefacts:\n  {}\n\n\
         Run `cargo xtask codegen` and commit the result.",
        stale.len(),
        stale.join("\n  ")
    ))
}

fn main() -> ExitCode {
    let result = match std::env::args().nth(1).as_deref() {
        Some("fetch") => fetch::run_fetch(),
        Some("codegen") => run(false),
        Some("check") => run(true),
        Some(other) => Err(format!("unknown task {other:?}\n\n{USAGE}")),
        None => Err(format!("no task given\n\n{USAGE}")),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}
